/* Retail sales Data analysis*/

CREATE DATABASE RETAIL;
USE RETAIL;

CREATE TABLE DEMOGRAPHIC_RAW(
AGE_DESC VARCHAR(20),
MARITAL_STATUS_CODE VARCHAR(4),
INCOME_DESC VARCHAR(40),
HOMEOWNER_DESC VARCHAR(40),
HH_COMP_DESC VARCHAR(50),
HOUSEHOLD_SIZE_DESC VARCHAR(50),
KID_CATEGORY_DESC VARCHAR(40),
HOUSEHOLD_KEY INT PRIMARY KEY);

CREATE TABLE CAMPAIGN_DESC_RAW(
DESCRIPTION CHAR(10),
CAMPAIGN INT,
START_DAY INT,
END_DAY INT,
PRIMARY KEY(DESCRIPTION),
UNIQUE (CAMPAIGN));

CREATE TABLE CAMPAIGN_RAW(
DESCRIPTION CHAR(10),
HOUSEHOLD_KEY INT,
CAMPAIGN INT,
FOREIGN KEY(CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN),
FOREIGN KEY(HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAW(HOUSEHOLD_KEY),
FOREIGN KEY(DESCRIPTION)REFERENCES CAMPAIGN_DESC_RAW(DESCRIPTION));

CREATE TABLE PRODUCT_RAW(
PRODUCT_ID	INT PRIMARY KEY,
MANUFACTURER 	INT,
DEPARTMENT	VARCHAR(40),
BRAND	VARCHAR(10),
COMMODITY_DESC	VARCHAR(65),
SUB_COMMODITY_DESC VARCHAR(65),
CURR_SIZE_OF_PRODUCT VARCHAR(15));

CREATE TABLE COUPON_RAW(
COUPON_UPC	INT,
PRODUCT_ID	INT,
CAMPAIGN INT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN));

CREATE TABLE COUPON_REDEMPT_RAW(
HOUSEHOLD_KEY	INT,
DAY	INT,
COUPON_UPC	INT,
CAMPAIGN INT,
FOREIGN KEY (HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAW(HOUSEHOLD_KEY),
FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN));

CREATE TABLE TRANSACTION_RAW( 
HOUSEHOLD_KEY INT,
BASKET_ID INT,
DAY	INT,
PRODUCT_ID	INT,
QUANTITY	INT,
SALES_VALUE	FLOAT,
STORE_ID	INT,
RETAIL_DISC	FLOAT,
TRANS_TIME	INT,
WEEK_NO	INT,
COUPON_DISC	INT,
COUPON_MATCH_DISC INT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAW(HOUSEHOLD_KEY));