// RETAIL DATA ANALYSIS PROJECT//

CREATE WAREHOUSE RETAIL;
CREATE DATABASE RETAIL;
USE DATABASE RETAIL;

CREATE SCHEMA RETAIL_SCHEMA;
USE SCHEMA RETAIL_SCHEMA;

CREATE OR REPLACE TABLE DEMOGRAPHIC_RAW(
AGE_DESC VARCHAR(20),
MARITAL_STATUS_CODE VARCHAR(4),
INCOME_DESC VARCHAR(40),
HOMEOWNER_DESC VARCHAR(40),
HH_COMP_DESC VARCHAR(50),
HOUSEHOLD_SIZE_DESC VARCHAR(50),
KID_CATEGORY_DESC VARCHAR(40),
HOUSEHOLD_KEY INT PRIMARY KEY);

CREATE OR REPLACE TABLE CAMPAIGN_DESC_RAW(
DESCRIPTION CHAR(10),
CAMPAIGN INT,
START_DAY INT,
END_DAY INT,
PRIMARY KEY(DESCRIPTION),
UNIQUE (CAMPAIGN));


CREATE OR REPLACE TABLE CAMPAIGN_RAW(
DESCRIPTION CHAR(10),
HOUSEHOLD_KEY INT,
CAMPAIGN INT,
FOREIGN KEY(CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN),
FOREIGN KEY(HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAW(HOUSEHOLD_KEY),
FOREIGN KEY(DESCRIPTION)REFERENCES CAMPAIGN_DESC_RAW(DESCRIPTION));

CREATE OR REPLACE TABLE PRODUCT_RAW(
PRODUCT_ID	INT PRIMARY KEY,
MANUFACTURER 	INT,
DEPARTMENT	VARCHAR(40),
BRAND	VARCHAR(10),
COMMODITY_DESC	VARCHAR(65),
SUB_COMMODITY_DESC VARCHAR(65),
CURR_SIZE_OF_PRODUCT VARCHAR(15));

CREATE OR REPLACE TABLE COUPON_RAW(
COUPON_UPC	INT,
PRODUCT_ID	INT,
CAMPAIGN INT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN));

CREATE OR REPLACE TABLE COUPON_REDEMPT_RAW(
HOUSEHOLD_KEY	INT,
DAY	INT,
COUPON_UPC	INT,
CAMPAIGN INT,
FOREIGN KEY (HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAW(HOUSEHOLD_KEY),
FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN));

CREATE OR REPLACE TABLE TRANSACTION_RAW( 
HOUSEHOLD_KEY INT,
BASKET_ID INT,
DAY	INT,
PRODUCT_ID	INT,
QUANTITY	INT,
SALES_VALUE	FLOAT,
STORE_ID	INT,
RETAIL_DISC	FLOAT,
TRANS_TIME	INT,
WEEK_NO	INT,
COUPON_DISC	INT,
COUPON_MATCH_DISC INT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_RAW(PRODUCT_ID),
FOREIGN KEY (HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAW(HOUSEHOLD_KEY));

---------------------------------------
-- CREATE STORAGE INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION  s3_int_retail
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::484925741514:role/RETAIL_ROLE'
STORAGE_ALLOWED_LOCATIONS = ('s3://sk.retails.bucket/');

DESC STORAGE INTEGRATION s3_int_retail;

--------FILE FORMAT-------
CREATE OR REPLACE FILE FORMAT RETAILCSV
TYPE = CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RETAIL_STAGE
URL =  's3://sk.retails.bucket/'     --  (Name of your bucket)
FILE_FORMAT = RETAILCSV
STORAGE_INTEGRATION = s3_int_retail;

SHOW STAGES;

-- CREATE SNOWPIPE THAT RECOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO EXISTING TABLE
-- The AUTO_INGEST=true parameter specifies to read 
-- event notifications sent from an S3 bucket to an SQS queue when new data is ready to load.
-- create separate Snowpipes for each dataset.--

CREATE OR REPLACE PIPE SNOWPIPE_DEMOGRAPHIC_RAW
AUTO_INGEST = TRUE 
AS COPY INTO RETAIL.RETAIL_SCHEMA.DEMOGRAPHIC_RAW --table NAME DEMOGRAPHIC_RAW that you created in snowflake)
FROM @RETAIL_STAGE/DEMOGRAPHIC/         ---------s3 bucket subfolder name
FILE_FORMAT = RETAILCSV;

CREATE OR REPLACE PIPE SNOWPIPE_CAMPAIGN_DESC_RAW
AUTO_INGEST = TRUE 
AS COPY INTO RETAIL.RETAIL_SCHEMA.CAMPAIGN_DESC_RAW
FROM @RETAIL_STAGE/CAMPAIGN_DESC/
FILE_FORMAT = RETAILCSV;
SHOW PIPES;

CREATE OR REPLACE PIPE SNOWPIPE_PRODUCT_RAW
AUTO_INGEST = TRUE 
AS COPY INTO RETAIL.RETAIL_SCHEMA.PRODUCT_RAW
FROM @RETAIL_STAGE/PRODUCT/
FILE_FORMAT = RETAILCSV;

CREATE OR REPLACE PIPE SNOWPIPE_TRANSACTION_RAW
AUTO_INGEST = TRUE 
AS COPY INTO RETAIL.RETAIL_SCHEMA.TRANSACTION_RAW
FROM @RETAIL_STAGE/TRANSACTION/
FILE_FORMAT = RETAILCSV;

CREATE OR REPLACE PIPE SNOWPIPE_CAMPAIGN_RAW
AUTO_INGEST = TRUE 
AS COPY INTO RETAIL.RETAIL_SCHEMA.CAMPAIGN_RAW
FROM @RETAIL_STAGE/CAMPAIGN/
FILE_FORMAT = RETAILCSV;

-- campaign pipe
CREATE OR REPLACE PIPE SNOWPIPE_CAMPAIGN_RAW
AUTO_INGEST = TRUE 
AS
COPY INTO RETAIL.RETAIL_SCHEMA.CAMPAIGN_RAW
FROM @RETAIL_STAGE/CAMPAIGN/
FILE_FORMAT = RETAILCSV
PATTERN = '.*\.csv';  -- or more specific like '.*campaign.*\.csv'


CREATE OR REPLACE PIPE SNOWPIPE_COUPON_RAW
AUTO_INGEST = TRUE 
AS COPY INTO RETAIL.RETAIL_SCHEMA.COUPON_RAW
FROM @RETAIL_STAGE/COUPON/
FILE_FORMAT = RETAILCSV;

CREATE OR REPLACE PIPE SNOWPIPE_COUPON_REDEMPT_RAW
AUTO_INGEST = TRUE 
AS COPY INTO RETAIL.RETAIL_SCHEMA.COUPON_REDEMPT_RAW
FROM @RETAIL_STAGE/COUPON_REDEMPT/
FILE_FORMAT = RETAILCSV;

SHOW PIPES;
SHOW STAGES;
-- REFRESH DATA IN IN BUCKET--

ALTER PIPE SNOWPIPE_DEMOGRAPHIC_RAW REFRESH;
ALTER PIPE SNOWPIPE_CAMPAIGN_DESC_RAW REFRESH;
ALTER PIPE SNOWPIPE_CAMPAIGN_RAW REFRESH;
ALTER PIPE SNOWPIPE_PRODUCT_RAW REFRESH;
ALTER PIPE SNOWPIPE_TRANSACTION_RAW REFRESH;
ALTER PIPE SNOWPIPE_COUPON_REDEMPT_RAW REFRESH;
ALTER PIPE SNOWPIPE_COUPON_RAW REFRESH;

SHOW PIPES;
DESC STAGE RETAIL_STAGE;

------TOTAL RECORDS IN TABLES--

SELECT COUNT(*) FROM DEMOGRAPHIC_RAW;
SELECT COUNT(*) FROM CAMPAIGN_DESC_RAW;
SELECT COUNT(*) FROM CAMPAIGN_RAW;
SELECT COUNT(*) FROM COUPON_RAW;
SELECT COUNT(*) FROM COUPON_REDEMPT_RAW;
SELECT COUNT(*) FROM PRODUCT_RAW;
SELECT COUNT(*) FROM TRANSACTION_RAW;

SELECT * FROM CAMPAIGN_RAW LIMIT 10;
SELECT * FROM CAMPAIGN_DESC_RAW LIMIT 10;
SELECT * FROM COUPON_RAW LIMIT 10;
SELECT * FROM COUPON_REDEMPT_RAW LIMIT 10;
SELECT * FROM DEMOGRAPHIC_RAW LIMIT 10;
SELECT * FROM PRODUCT_RAW LIMIT 10;
SELECT * FROM TRANSACTION_RAW LIMIT 10;

